### PR TITLE
:pencil: Spelling corrections for prereq

### PR DESCRIPTION
**Pull request by sunnivin**
Some new suggestions for tutorials I think are useful to know about for new users. 

Emigrated from the [old prereq template](https://sunnivin.github.io/rtd-github-pages/en/master/prereqs.html).

### CODE REVIEW

**Comment by sunnivin** [comment]
@gunnartl, could you please let me know if I missed something from your old idea?

**Review by gunnartl — APPROVED** [review]
Looks great!

**Comment by gunnartl** [comment]
The hyperlink syntax does not seem to be the same inside the discussion blocks, or is it just my computer acting up again?

**Comment by sunnivin** [comment]
> The hyperlink syntax does not seem to be the same inside the discussion blocks, or is it just my computer acting up again?

To make it easier to maintain I changed all the `.rst` files to the `.md` format. When you build the page it will look the same.

**Comment by sunnivin** [comment]
You can see it [here](https://metos-uio.github.io/CTSM-Norway-Documentation/prerequisite/)

**Comment by gunnartl** [comment]
I see. 
nothing missing as far as i can see, and it looks supersmooth :+1:

**Pull request merged**
